steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - "--ciphertext-file=settings.py.enc"
      - "--plaintext-file=settings.py"
      - "--location=global"
      - "--keyring=line-bot"
      - "--key=sagawa-notice-line-bot"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - sagawa-notice-line-bot
      - --region=asia-northeast1
      - --source=.
      - --trigger-topic=sagawa-notice-line-bot
      - --runtime=python39
